name: test-task

groups:
  - name: 常用
    shortcutPrefix: q

  - name: 其他
    shortcutPrefix: w

tags:
  - name: 百分比
    label: 百分比
    abbr: PERC
    shortcut: '1'
    theme:
      background: '#97eb49'

  - name: 机构名
    label: 机构名
    abbr: ORG
    shortcut: '2'
    theme:
      background: '#66CC99'

  - name: 人名
    group: 常用
    label: 人名
    shortcut: q
    abbr: PER
    theme:
      background: '#FF99CC'

  - name: 地名
    group: 常用
    label: 地名
    shortcut: w
    abbr: LOC
    theme:
      background: '#66CCFF'

  - name: 货币
    group: 常用
    label: 货币
    shortcut: e
    abbr: ￥
    theme:
      background: '#9a9deb'

  - name: 日期
    label: 日期
    group: 常用
    shortcut: r
    abbr: DATE
    theme:
      background: '#FF6666'

  - name: 时间
    label: 时间
    group: 常用
    shortcut: t
    abbr: TIME
    theme:
      background: '#FFCC00'

  - group: 其他
    name: 非货币数量词
    label: 非货币数量词
    shortcut: 'q'
    abbr: '[非货币数量词]'
    theme:
      background: '#bdbdbd'

  - group: 其他
    name: 行业
    label: 行业
    shortcut: 'w'
    abbr: '[行业]'
    theme:
      background: '#bdbdbd'
